---
title: "Character Class Victory Conditions in League of Legends"
author: "Ethan Swartzentruber"
date: "12/10/2019"
output: pdf_document
---

# Abstract

In the computer game League of Legends, players choose from 146 different characters at the start of the game. These characters are divided into six different categories by the game's developer, Riot Games (often simply called Riot). This analysis uses logistic regression in an attempt to determine to what extent this division is valid - in particular, whether the division of characters presented by Riot captures a concrete difference in victory conditions of the character classes. Although the conventional wisdom amongst the League of Legends community is that these character classes should represent a stark difference in victory condition, this analysis failed to find a statistical basis for the existence of such a difference.

# Introduction

League of Legends is an extremely popular 5v5 competitive strategy game. Players join a queue to be matched with other players of a comparable skill level, and at the beginning of each game, choose from a roster of 146 (as of Dec 10 2019) playable characters. Each of these characters is unique, and in the ranked 5v5 format (the format which this analysis uses data from), only one player can choose a given character in each game. These characters are divided into six classes by Riot Games, the developer and publisher of League of Legends: Assassin, Fighter, Mage, Marksman, Support, and Tank. These classes differ greatly in aesthetic theme and in how they feel to the player. For example, some classes are built for one versus one duels with enemy players, and some are built to thrive in conflicts involving the entirity of both teams. The conventional wisdom amongst the League of Legends community is that these character classes differ in the degree to which they are _individualistic_ - the degree to which it is required that the character be played well, rather than simply be on a team which has some collective advantage, in order to win.

There are several different types of concrete advantage to be had in League of Legends that this study considers. The first is _gold_. Gold is granted in some quantity by almost every activity in League of Legends, and is used to buy items, which make the players' characters more powerful. This is one of two individual progression systems in League of Legends. The second type of individual advantage is _experience_. Experience points are granted to players who are standing in a radius of neutral or enemy units when they die, and occasionally through several other mechanisms which are specific to certain characters. Hitting thresholds of experience causes your character to level up, which makes your character more powerful. 

In addition to individual advantage, there are two types of collective advantage which this analysis considers. The first is _neutral monsters_. These are large monsters which are in limited supply in a game of League of Legends - once a team has killed the monster, the other team cannot kill it. Each of these monsters grants a permanent power bonus to every player on the team which killed it. The second type of collective advantage is _destroyed buildings_. Both teams start with a set of structures on their side of the map, which provide defense. These buildings can be destroyed by the opposing team, and most of them do not respawn.

# Data

## Data Collections

The 8064 games which comprise the data for this analysis was collected via Riot Games' public API. Usage of this API involved first requesting the list of games for a specific player, and then processing each of those games. In order to maintain stability in the underlying patterns in gameplay, I chose to sample names from a continuous section of the League of Legends leaderboard - all the games here are played by players of comparable rank. Because Riot Games does not publish an official leaderboard that is easily scrapable, I used a third party leaderboard from the website https://www.op.gg/ . THis leaderboard is extremely close to the official leaderboard - it is determined by the players' in-game ranking and is mostly up to date. I chose to sample from just inside the 95th percentile of players, because ranks much higher than that caused the population of players to shrink to the point where the observations were no longer independent, because the same games were appearing in the histories of multiple players in the sample.

## Data Dictionary

* **assists** (Numeric): How many times the player assisted in a kill during the game
* **ccScore** (Numeric): Number of seconds the player spent inhibiting the movement of enemy players in the game, weighted by number of players and type of movement inhibiting effect (this figure is provided by Riot API)
* **championClass** (Categorical): Which class of character the player was playing during the game
* **deaths** (Numeric): How many times the player died during the game   
* **firstBaron** (Categorical): Which team killed the first Baron, a late game neutral monster.
* **firstBloodKill** (Binary): Whether the player got the first kill of the game.
* **firstDragon** (Categorical): Which team killed the first Dragon, a neutral monster.         * **firstTower** (Categorical): Which team destroyed the first tower, a defensive building
* **fiveMinuteGoldDelta** (Numeric): Difference between the player of interest's gold total at 5 minutes and the average for the game
* **fiveMinuteXPDelta** (Numeric): Difference between the player of interest's experience total at 5 minutes and the average for the game
* **goldEarned** (Numeric): Total amount of gold earned by the player during the game
* **kills** (Numeric): How many kills the player achieved during the game
* **wardKills** (Numeric): Number of "wards" (units which observe the enemy players to gather information) killed by the player
* **win** (Binary Response): Whether the player of interest won the game

# Model

## Exploratory Data Analysis

## Model Selection

## Model Assessment

# Conclusions

## Limitations


